version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PG_HOST=172.18.0.1 # Nama container Postgres di docker-compose.yml
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DB=usercrudgolangdb

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usercrudgolangdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80" # PGAdmin available on localhost:8081
    depends_on:
      - db

volumes:
  postgres_data:
